CREATE TABLE urls(
    id BIGSERIAL PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_key TEXT UNIQUE NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);