// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int64            `json:"id"`
	OriginalUrl string           `json:"original_url"`
	ShortKey    string           `json:"short_key"`
	Clicks      int32            `json:"clicks"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
