// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls(original_url, short_key)
VALUES($1,$2)
RETURNING id, original_url, short_key, clicks, created_at
`

type CreateURLParams struct {
	OriginalUrl string `json:"original_url"`
	ShortKey    string `json:"short_key"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.OriginalUrl, arg.ShortKey)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortKey,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const getURL = `-- name: GetURL :one
SELECT id, original_url, short_key, clicks, created_at FROM urls
WHERE short_key = $1
LIMIT 1
`

func (q *Queries) GetURL(ctx context.Context, shortKey string) (Url, error) {
	row := q.db.QueryRow(ctx, getURL, shortKey)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortKey,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const incrementClick = `-- name: IncrementClick :exec
UPDATE urls
SET clicks = clicks + 1
WHERE id = $1
`

func (q *Queries) IncrementClick(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementClick, id)
	return err
}
